// Database table types (autogenerated from schema)
export interface Household {
  id: string;
  created_at: string;
}

export interface User {
  id: string;
  email: string;
  name?: string;
  household_id: string;
  created_at: string;
  updated_at: string;
}

export interface List {
  id: string;
  name: string;
  type: 'supermarket' | 'pharmacy' | 'house';
  household_id: string;
  created_at: string;
  updated_at: string;
}

export interface Item {
  id: string;
  list_id: string;
  name: string;
  qty?: string;
  section_id?: string;
  ticked: boolean;
  order_index: number;
  created_by_user_id: string;
  created_at: string;
  updated_at: string;
}

export interface ListSnapshot {
  id: string;
  list_id: string;
  items_snapshot: Item[];
  created_at: string;
}

export interface InviteToken {
  id: string;
  household_id: string;
  token_hash: string;
  consumed_by_user_id?: string;
  expires_at: string;
  created_at: string;
}

export interface CategorizationCache {
  id: string;
  item_name: string;
  list_type: 'supermarket' | 'pharmacy' | 'house';
  section_id: string;
  created_at: string;
}
